MODEL:
  TYPE: vssm
  NAME: vssm_tiny
  DROP_PATH_RATE: 0.2
  VSSM:
    EMBED_DIM: 24
    DEPTHS: [ 1, 1, 4, 1 ]
    SSM_D_STATE: 16
    SSM_DT_RANK: "auto"
    SSM_RATIO: 2.0
    SSM_FORWARDTYPE: "v2"
    MLP_RATIO: 0.0
    DOWNSAMPLE: "v2"
    PATCHEMBED: "v2"
    # SSM_FORWARDTYPE: "v0" # if you want exactly the same